name: "Scan Docker image from docker hub"

on:
  push:
    branches:
      - main

env:
  VERSION: $(( $(cat version.txt) + 1 ))

jobs:
  scan_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker hub
        run: echo "${{secrets.DOCKERHUB_TOKEN}}"| docker login -u "${{secrets.DOCKERHUB_USERNAME}}" --password-stdin

      - name: Get Docker Image
        run: | 
          docker pull docker.io/veereshonce/supermario:"${{ env.VERSION }}"
          docker save -o supermariolatestdockerimage.tar docker.io/veereshonce/supermario:"${{ env.VERSION }}"

      - name: Run Trivy Vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: /github/workspace/supermariolatestdockerimage.tar
          exit-code: '1'
          severity: 'CRITICAL,HIGH'